apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spring-boot-crac-demo
  name: spring-boot-crac-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-boot-crac-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-boot-crac-demo
        app.kubernetes.io/part-of: spring-boot-crac-demo
    spec:
      containers:
      - image: springdeveloper/spring-boot-crac-demo:checkpoint-amd64
        imagePullPolicy: IfNotPresent
        name: app
        env:
        - name: REVISION_NAME
          value: "crac-demo"
        - name: REVISION_UID
          value: "00001"
        - name: CRAC_FILES_DIR
          value: /var/crac/${REVISION_NAME}/${REVISION_UID}
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          runAsUser: 0
          capabilities:
            add:
            - CHECKPOINT_RESTORE
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        volumeMounts:
        - name: crac-cache
          mountPath: /var/crac
      volumes:
      - name: crac-cache
        persistentVolumeClaim:
          claimName: spring-crac-cache
