apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-crac-cache
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: "standard"
