apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crac-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: "standard"
